config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :show

  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update', as: :task

  delete 'tasks/:id/destroy', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def application
  end

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :detail, :complete)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
      <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Index", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Task", tasks_new_path, class: "nav-link" %>
      </li>

    </ul>
  </div>
</div>

app/views/tasks/_form.html.erb
<div class="card-new">
  <div class="new-task">
      <div class="flex-container sm">
        <%= form_for(@task) do |f| %>
          <%= f.label :title %>
          <%= f.text_field :title %>
          <%= f.label :detail %>
          <%= f.text_field :detail %>
          <%= f.label :complete %>
          <%= f.check_box :complete %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
</div>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<ul class="container">
  <% @tasks.each do |task| %>
        <li class="card-category">
          <div class="title">
            <p>Task: <%= task.title %></p>
          </div>
          <div class="text">
            <% if task.complete %>
              <p>[x] - Task completed </p>
            <% else  %>
              <p>[ ] - Task not completed </p>
            <% end  %>
          </div>
            <%= link_to 'Edit', edit_path(task) %>
            <%= link_to 'Delete', destroy_path(task), method: :delete %>
            <%= link_to 'Show', show_path(task) %>
        </li>
    <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div class="container-show">
  <div class="title-show">
    <%= @task.title %>
  </div>
    <div class="complete-show">
    <% if @task.complete %>
      [x]
    <% else %>
      [ ]
    <% end %>
    <%= @task.detail %>
  </div>
</div>